version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8090:80"
        volumes:
            - ./web:/web
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./web:/web
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
